name: Release

on:
  pull_request:
#  release:
#    types: [ published ]

jobs:
  hatch-release:
    uses: pyiron/actions/.github/workflows/hatch-release.yml@actions-4.0.10
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower-bounds.yml'
      publish-to-pypi: ${{ github.event_name == 'release' && github.event.action == 'published' }}
